# Generated by Django 6.0.7 on 2026-07-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FutStk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('fut', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=15)),
                ('high', models.DecimalField(decimal_places=4, max_digits=15)),
                ('low', models.DecimalField(decimal_places=4, max_digits=15)),
                ('close', models.DecimalField(decimal_places=4, max_digits=15)),
                ('volume', models.BigIntegerField()),
                ('oi', models.BigIntegerField()),
            ],
            options={
                'db_table': 'futstk_table',
            },
        ),
    ]
